
getwd()
setwd("~/Documents/Tunaatlas_level1")
require(remotes)
require(devtools)
# install_github("eblondel/geoflow", dependencies = c("Depends", "Imports"))
library(geoflow)
require(RPostgreSQL)
library(RPostgres)
library(RSQLite)
library(gsheet)
library(rtunaatlas)
library(DBI)
library(readr)
library(data.table)
library(rpostgis)
library(stringr)
library(sf)
library(googledrive)
executeWorkflow("from_scratch/json/tunaatlas_qa_global_datasets_catch.json")
