---
title: "Summary of the treatment for each entity of the global tuna atlas"
output:
  html_document: default
  word_document: default
date: '2022-03-23'
params:
  working_directory: "~/Documents/Tunaatlas_level1/jobs/all_25_avril"
  species_filter: !r c('YFT','SKJ', 'BET')
---

Analyse of the entity : `r params$working_directory`

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = TRUE,
	warning = TRUE
)
library(readtext)
library(flextable)
set_flextable_defaults(
  font.size = 30,
  font.color = "black",
  table.layout = "fixed",
  digits = NULL,
  theme_fun = "theme_box"
  )
library(dplyr)
library(stringr)
library(readr)
library(webshot)
if(require("htmltools"))
div(flextable_html_dependency())

```

```{r}
nominal_dataset <- readRDS("data/nominalmapped.rds")

if(!(is.null(params$species_filter))){nominal <- sum((nominal_dataset %>% filter(species %in% params$species_filter))$value)} else {nominal <- sum(nominal_dataset$value)}

# if(params$species =="main"){nominal <- 182299925}else{nominal<- 211479421}
```

The filter done is on : `r params$species_filter`.

```{r results='asis'}
FitFlextableToPage <- function(ft, pgwidth = 6){
    table <- flextable(ft) %>% autofit() %>% fit_to_width(30)

table %>% 
  color(~ `Difference (in % of tons)` < 0, color = "green",~ `Difference (in % of tons)`) %>% 
  color(~ `Difference (in % of tons)` >0, color = "red",~ `Difference (in % of tons)`)%>% 
  colformat_num(col_keys = c("`Difference (in % of fish)`"), digits = 2) %>%   color(~ `Difference (in % of fish)` < 0, color = "green",~ `Difference (in % of fish)`) %>% 
  color(~ `Difference (in % of fish)` >0, color = "red",~ `Difference (in % of fish)`)%>% 
  colformat_num(col_keys = c("`Difference (in % of lines)`"), digits = 2) %>%color(~ `Difference (in % of lines)` < 0, color = "green",~ `Difference (in % of lines)`) %>% 
  color(~ `Difference (in % of lines)` >0, color = "red",~ `Difference (in % of lines)`)%>% 
  colformat_num(col_keys = c("`Difference (in % of lines)`"), digits = 2) %>% flextable_to_rmd()

}
```

```{r}
list_dir <- list.dirs(path =paste0(params$working_directory, "/entities"), full.names = TRUE, recursive = FALSE)
```

```{r}
list <- c()
for (sub_list_dir in list_dir){
  # list_options <- read_csv(paste0(sub_list_dir,"/list_options.csv"))
  #     assign(paste0(tail(str_split(paste0(sub_list_dir),"/")[[1]],n=1), "list_options"), list_options, envir = .GlobalEnv)
  # print(sub_list_dir)
    sub_list_dir_2 <- list.dirs(path =paste0(sub_list_dir,"/Markdown"), full.names = TRUE, recursive = FALSE)
    details = file.info(paste0(sub_list_dir_2,"/Markdown"))
    details = file.info(sub_list_dir_2)
    details = details[with(details, order(as.POSIXct(mtime))), ]
    sub_list_dir_2 = rownames(details)
  df <- data.frame(matrix(ncol =10, nrow = 1))
  colnames(df) <- c(paste0(tail(str_split(paste0(sub_list_dir),"/")[[1]],n=1)),
                    # "Explanation", "Fonctions", 
                    "Options", "Sum in tons", "Sum in number of fish", "Number of lines","Difference (in % of tons)","Difference in tons","Difference (in % of fish)", "Difference (in % of lines)", "Percentage of nominal"
                    )
  if((!is.null(params$species_filter))){
  tons_init <- pull(read.csv(paste0(sub_list_dir_2[1],"/sums.csv"))[1])
  lines_init <- pull(read.csv(paste0(sub_list_dir_2[1],"/sums.csv"))[3])
  nofish_init <- pull(read.csv(paste0(sub_list_dir_2[1],"/sums.csv"))[2])} else{
     main <- readRDS(paste0(sub_list_dir_2[1],"/rds.rds")) %>% filter(species%in%params$species_filter)
      tons_init <- sum((main %>% filter(unit%in%c("MTNO", "MT")))$value)
      nofish_init <- sum((main %>% filter(unit%in%c("NOMT", "NO")))$value)
      lines_init <- nrow(main)
  }
    for (i in sub_list_dir_2){
      # sum((nominal_dataset %>% filter(year(time_start) > min(data$year)))$value) filtered only on species presented in georefdataset filte
      # nominal <- 211479421
      #this is not the complete sum o nominal, indeed it is the one between 1950 and 2020


      sums <- read.csv(paste0(i,"/sums.csv"))
      Explanation <- readtext(paste0(i,"/explication.txt"))[2]
      Fonctions <- pull(readtext(paste0(i,"/fonctions.txt"))[2])
      if (file.exists(paste0(i,"/options.txt"))){
        Options <- pull(readtext(paste0(i,"/options.txt"))[2])} else {Options <- "Aucune"}
      if(!is.null(params$species_filter)){
      main <- readRDS(paste0(i,"/rds.rds")) %>% filter(species%in%params$species_filter)
      sum_t <- sum((main %>% filter(unit%in%c("MTNO", "MT")))$value)
      sum_no <- sum((main %>% filter(unit%in%c("NOMT", "NO")))$value)
      nrow <- nrow(main)
      
      } else{sum_t <- pull(sums[1])
      sum_no <-  pull(sums[2])
      nrow <- pull(sums[3])}
      
      step <- tail(str_split(paste0(i),"/")[[1]],n=1)
      loss_percent <- 100*((tons_init - sum_t)/tons_init)
      loss_tons <- (tons_init - sum_t)
      loss_percent_lines <- 100*((lines_init - nrow)/lines_init)
      loss_percent_no <- 100*((nofish_init - sum_no)/nofish_init)
      percentage_of_nominal <- (sum_t*100)/nominal
      sums <- as.data.frame(data.frame(sum_t, sum_no, nrow))
      data_i <- cbind(step,
                      # Explanation, Fonctions, 
                      Options,
                      sums, loss_percent,loss_tons,loss_percent_no, loss_percent_lines, percentage_of_nominal)
      names(data_i) <- colnames(df)
      df <- rbind(df, data_i)
      tons_init <- sum_t
      nofish_init <- sum_no
      lines_init <- nrow

    }
  df = df[-1,]
  write_csv(df, paste0(sub_list_dir,"/table.csv"))
  assign(paste0(tail(str_split(paste0(sub_list_dir),"/")[[1]],n=1)), df, envir = .GlobalEnv)
  list <- append(list,tail(str_split(paste0(sub_list_dir),"/")[[1]],n=1))

}
```

```{r results='asis'}
for (i in list){
  FitFlextableToPage(eval(as.symbol(i)))
}

# lapply(list, FitFlextableToPage)
# FitFlextableToPage(global_catch_1deg_1m_ps_bb_ird_level1)
```
